apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-for-github
spec:
  params:
    - name: gitRepository
      value: $(body.repository.html_url)
    - name: commits
      value: $(body.commits)
