apiVersion: tekton.dev/v1beta1                                                    
kind: Pipeline                                                                   
metadata:
  name: clone-build-push                                   
spec:
  description: |                                                      
    Cet espace de travail contient les fichiers du dépôt clonés, afin qu'ils puissent être lus par le
    prochaine tâche
  params:                                                                     
    - name: repo-url                                                            
      type: string                                                       
    - name: image-reference-front                                             
      type: string                                                            
    - name: image-reference-api                                               
      type: string 
    - name: image-reference-back                                                  
      type: string 
  workspaces:                                              
    - name: shared-data                            
    - name: docker-credentials                            
  tasks:                                                            
    - name: clonage-du-depot     
      taskRef:
        name: git-clone           
      workspaces:
        - name: output                                                           
          workspace: shared-data                                         
      params:                                                                   
        - name: url                                                      
          value: $(params.repo-url)                                   
    - name: build-and-push-front-end          
      runAfter: ["clonage-du-depot"]                                              
      taskRef:
        name: kaniko                                                     
      workspaces:
        - name: source                                               
          workspace: shared-data         
          mountPath: /1_welcome
        - name: dockerconfig                                                     
          workspace: docker-credentials                                       
      params:                                                                
        - name: IMAGE                                                           
          value: $(params.image-reference-front)      
    - name: build-and-push-api                                                      
      runAfter: ["build-and-push-front-end"]                                           
      taskRef:
        name: kaniko                   
      workspaces:
        - name: source                                                           
          workspace: shared-data                                                 
          mountPath: "1_welcome/interne/Serv 6 chatbot/chatbot-main/chatbot-main"
        - name: dockerconfig                                                      
          workspace: docker-credentials                                           
      params:                                                               
        - name: IMAGE                                                         
          value: $(params.image-reference-api)                                        
    - name: build-and-push-backend                                                       
      runAfter: ["build-and-push-api"]                       
      taskRef:
        name: kaniko                                                
      workspaces:
        - name: source                                               
          workspace: shared-data                                                
          mountPath: /back
        - name: dockerconfig                                     
          workspace: docker-credentials       
      params:                                                                  
        - name: IMAGE                                                         
          value: $(params.image-reference-back)                                        