apiVersion: tekton.dev/v1beta1                                                 # Version de l'API Tekton utilisée
kind: PipelineRun                                                              # Type d'objet : Exécution de pipeline
metadata:
  generateName: clone-build-push-run-                                          # Préfixe pour les noms générés des exécutions de pipeline
spec:
  pipelineRef:                                                                 # Référence au pipeline à exécuter
    name: clone-build-push                                                     # Nom du pipeline à exécuter
  podTemplate:                                                                 # Modèle de pod pour l'exécution du pipeline
    securityContext:                                                           # Contexte de sécurité du pod
      fsGroup: 65532                                                           # GID du groupe pour les volumes montés
  workspaces:                                                                  # Espaces de travail utilisés par le pipeline
    - name: shared-data                                                        # Nom de l'espace de travail partagé
      volumeClaimTemplate:                                                     # Modèle de demande de revendication de volume
        spec:                                                                  # Spécification de la demande de revendication de volume
          accessModes:                                                         # Modes d'accès au volume
            - ReadWriteOnce                                                    # Mode de lecture-écriture unique
          resources:                                                           # Ressources allouées au volume
            requests:                                                          # Ressources demandées pour le volume
              storage: 2Gi                                                     # Taille du stockage demandée (2 gigaoctets)
    - name: docker-credentials                                                 # Nom de l'espace de travail pour les informations d'identification Docker
      secret:                                                                  # Spécification d'un secret Kubernetes
        secretName: docker-credentials                                         # Nom du secret contenant les informations d'identification Docker
  params:                                                                      # Paramètres à fournir au pipeline
    - name: repo-url                                                           # Nom du paramètre pour l'URL du dépôt
      value: https://github.com/Tidjene/myrepo.git                             # Valeur de l'URL du dépôt
    - name: image-reference                                                    # Nom du paramètre pour la référence d'image
      value: tidix/public:frontend                                             # Valeur de la référence d'image
